app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from . import login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key = True)
    first_name = db.Column(db.String(255))
    last_name = db.Column(db.String(255))
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    pass_secure = db.Column(db.String(255))
    comments = db.relationship('Comments', backref = 'comments', lazy = 'dynamic')
    pitch = db.relationship('Pitch', backref = 'pitches', lazy = 'dynamic')
    
    
    @property
    def password(self):
        raise AttributeError('You do not have permission to view password attribute')
    
    
    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)


    def save_user(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'User: {self.username}'
    
    
 
 
class Pitch(db.Model):
    __tablename__ = 'pitch'
    
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255))
    body = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    comments = db.relationship('Comments', backref='comments1', lazy='dynamic')


    def save_pitch(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def get_pitches(cls, category):
        pitches = Pitch.query.filter_by(category = category).all()
        return pitches
    
    
    def get_pitch(cls, id):
        pitch = Pitch.query.filter_by(id = id).first()
        return pitch
    
    
    @classmethod
    def count_pitches(cls, uname):
        user = User.query.filter_by(username = uname). first()
        pitches = Pitch.query.filter_by(user_id = user.id).all()
        
        pitches_count = 0
        for pitch in pitches:
            pitches_count += 1
            
        return pitches_count
    
    def get_comments(self):
        pitch = Pitch.query.filter_by(id = self.id).first()
        comments = Comments.query.filter_by(pitch = pitch.id)
        return comments
    
    
    def __repr__(self):
        return f'Pitch: {self.body}'






class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    posted = db.Column(db.DateTime, default = datetime.utcnow)  
    pitch = db.Column(db.Integer, db.ForeignKey('pitch.id'))
    
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()


    @classmethod
    def get_comments(cls, pitch):
        comments = Comments.query.filter_by(pitch_id = pitch).all()
        return comments


    def __repr__(self):
        return f'Comment: {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, ValidationError, IntegerField, SelectField
from wtforms.validators import Required, Email
from ..models import User


class PitchForm(FlaskForm):
    
    title = StringField('Pitch title',validators=[Required()])
    
    body = TextAreaField('Pitch post')

    submit = SubmitField('Submit')
    
    
    
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators= [Required()])
    submit = SubmitField('Submit')
    
    
class CommentForm(FlaskForm):
  comment = StringField('Your comment:')
  submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet
from config import config_options


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()
simple = SimpleMDE()


def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)

    # Registering the blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import Flask, render_template, request, redirect, url_for, abort, flash
from . import main
from .forms import PitchForm, CommentForm
from ..models import User, Pitch, Comments
# from ..pitches import get_pitch
from flask_login import login_required, current_user
from .. import db
import markdown2
import datetime


@main.route('/')
@login_required
def index():
    pitches=Pitch.query.all()
    
    title = 'Welcome to Pitch'
    
    return render_template('index.html', title = title, pitches=pitches[::-1])



@main.route('/profile/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    user_id = User.id
    pitches = Pitch.query.filter_by(user_id=user_id).all()
    # pitches_count = Pitch.count_pitches(uname)
    message="You don't have any pitches."
    if pitches is not 0:
        message="These are your pitches:"
        
        
    if user is None:
        abort(404)
        
    return render_template('profile/profile.html', user = user, pitches = pitches, message = message)


@main.route('/writing-pitch', methods=['GET', 'POST'])
@login_required
def write_pitch():
    form = PitchForm()
    if form.validate_on_submit():
    
        pitch = Pitch(title=form.title.data, body=form.body.data)

        db.session.add(pitch)
        db.session.commit()
        return redirect(url_for('.index'))

    title = 'New Pitch'
    return render_template('new_pitch.html', pitch=form, title=title)




@main.route('/view-comments/<id>')
def view_comments(id):
    pitch = Pitch.query.filter_by(id=id)
    comments = Comments.query.filter_by(id=id)
    message='This pitch has no comments'
    if comments is not 0:
        message=f"You're now viewing the comments. Click home to continue browsing pitches"
    return render_template('comments.html', message=message, comments=comments, pitch=pitch)

@main.route('/delete/<id>')
def pitch_delete(id):
    pitch = Pitch.query.filter_by(id=id)
    return pitch.delete_pitch()

@main.route('/pitch/<int:id>',methods=['GET','POST'])
def pitch(id):
   pitch = Pitch.get_pitch(id, id)
   if request.args.get('like'):
       pitch.likes = pitch.likes + 1
       
       db.session.add(pitch)
       db.session.commit()
       
       return redirect('/pitch/{pitch_id}'.format(pitch_id = pitch.id))
   
   elif request.args.get('dislike'):
       pitch.dislikes = pitch.dislikes + 1
       
       db.session.add(pitch)
       db.session.commit()
       
       return redirect('/pitch/{pitch_id}'.format(pitch_id = pitch.id))
   comment_form = CommentForm()
   if comment_form.validate_on_submit():
       comment = Comments(comment = comment_form.comment.data)
       comment.save_comment()
       
       comments = Comments.get_comments(pitch)
       
       return render_template('pitch.html', pitch = pitch, comment=comment_form, comments = comments)


@main.route('/profile/<uname>/pitches')
def user_pitches(uname):
    user = User.query.filter_by(username = uname).first()
    pitches = Pitch.query.filter_by(user_id = user.id).all()
    pitches_count = Pitch.count_pitches(uname)
    
    return render_template('profile.pitches.html', user = user, pitches = pitches, pitches_count = pitches_count)




@main.route('/comment', methods=['GET', 'POST'])
@login_required
def write_comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comments(comment = form.comment.data)
        comment.save_comment()

        # return redirect(url_for('.index'))

    return render_template('comment.html', comment=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}
<body class="body" style="background-image:url('https://image.freepik.com/free-photo/white-marble-texture-background_38679-514.jpg')">
{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block styles %}
  {{super()}}]
  {{simplemde.css}}
  {{simplemde.js}}
{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  <div class="col-lg-12">
    {{wtf.quick_form(comment)}}
  </div>
</div>
{% endblock %}

app/templates/comments.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-2">
       <h4>{{message}}</h4>
      <hr>
      <p>{{macro.displayComments(comments)}}</p>
    </div>
  </div>
</div>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%} 

{% block content %}
    
    <h1>Sorry we cant find that page!</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block styles %}

    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
      
{% endblock %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script type="text/javascript" src="/app/particles.js">particlesJS("particles-js",<strong>particlesjs-config.json</strong>);</script>
    <title>Pitch</title>
</head>
<body class="body" style="background-image:url('https://image.freepik.com/free-photo/abstract-rustic-black-surface_23-2148287666.jpg')">
    <div id="particles-js">
        <h1 class="text-white text-center">Pitch Area</h1>
        <hr>
        <h2 class="text-white">{{ message }}</h2>
        {{macro.displayPitches(pitches)}}
    </div>

    <script type="text/javascript">
        particlesJS("particles-js",<strong>particlesjs-config.json</strong>);
    </script>
</body>
</html>
{% endblock %}

app/templates/macros.html
{% macro displayPitches(pitches_list) %}
  {% for pitch in pitches_list %}
  <div class="container">
    <!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"> -->
      <h1>{{pitch.title}}</h1>
      <h4>{{pitch.body}}</h4>
      <h4><a href='/comment'>Write a comment</a></h4>
      <a href="/view-comments/{{pitch.id}}" class="btn btn-primary text-center">Read comments</a>
      <p>Posted: {{ pitch.posted }}</p>
      <br>
      <br>
    </div>
  </div>
  {% endfor %}
{% endmacro %}
{% macro displayComments(comments_list) %}
{% for comment in comments_list %}
<div class="container">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <ul>
      <li><h4>{{comment.comment}}</h4></li>
    </ul>
    <h6>Posted: {{comment.posted}}</h6>
  </div>
</div>
{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class='navbar navbar-inverse' role='navigation'>
    <div class="container-fluid">
        <div class="navbar-header">
            <!-- <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
            <span class='sr-only'>Toggle Navigation</span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            </button> -->
            <a class='navbar-brand' href='/'>Pitch</a>
        </div>
        <div class='navbar-collapse collapse'>
            {% if current_user.is_authenticated %}
            <ul class='nav navbar-nav'>
                <li><a href='/'>Home</a></li>
             </ul>

            <ul class='nav navbar-nav navbar-right'>
            
                <li><a class='ratings' href='/writing-pitch'>New Pitch</a></li>

                <li style='color:white;'><a href="{{url_for('main.profile', uname=current_user.username)}}"> Profile</a></li>

                <!-- <li><a href="{{url_for('main.user_pitches',uname=current_user.username)}}">{{current_user.username}}'s Pitches</a></li> -->

                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>

            </ul>
            {% endif %}
        </div>
    </div>
</div>

app/templates/new_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
     <div class="col-md-8">
        <h3>Share a pitch: </h3>
        {{wtf.quick_form(pitch)}}
    </div>
</div>
{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles -%}
    {{super()}}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{% endblock %}

{% block content %}

<div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 well pitch-well">
    <div class="row">
        <h2>{{pitch.title}}</h2>
        <hr>
        <p>{{pitch.body}}</p>

        <span>
        <p>Posted on: {{pitch.posted}}</p>
        <a href ="/pitch/{{pitch.id}}?like=1"><i class="far fa-thumbs-up"></i></a>{{pitch.likes}}
        <a href ="/pitch/{{pitch.id}}?dislike=1"> <i class="far fa-thumbs-down"></i></a>{{pitch.dislikes}}
        </span>
    </div>
</div>
    
 {% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
        <h4>{{message}}</h4>

        <!-- <h3>Your Pitches:</h3> -->

        <p>{{macro.displayPitches(pitch)}}</p>
        
    </div>
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}